language: elixir
cache:
  directories:
  - deps
  - _build
addons:
  postgresql: "9.5"
elixir:
  - 1.3.4
  - 1.6.5
otp_release:
  - 18.2
  - 19.1
  - 20.3
env:
  global:
    - MIX_ENV=test
    - MAIN_BRANCHES="master develop staging" # Branches on which you want version to be incremented
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  # Run all tests except pending ones
  - "mix test --exclude pending --trace"
  # Submit code coverage report to Coveralls
  - "mix coveralls.travis"
  # Run static code analysis
  - "mix credo"
